name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2

    - name: Install Wally packages
      run: wally install

    - name: Build with Rojo
      run: rojo build default.project.json -o test-place.rbxl

    - name: Run tests in Roblox Cloud
      # 测试步骤：如果没有配置 secrets，脚本会友好提示
      env:
        ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        UNIVERSE_ID: ${{ secrets.UNIVERSE_ID }}
        TEST_PLACE_ID: ${{ secrets.TEST_PLACE_ID }}
      run: |
        if [ -z "$ROBLOX_API_KEY" ]; then
          echo "⚠️ Skipping cloud tests - ROBLOX_API_KEY not configured in repository secrets"
          echo "ℹ️ To enable cloud testing, add secrets: ROBLOX_API_KEY, UNIVERSE_ID, TEST_PLACE_ID"
          exit 0
        fi
        node scripts/test-in-roblox-cloud.js --skip-build -V

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: .test-result/
        retention-days: 30
