name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## 更新内容

          查看完整的更新日志，请参考提交历史。

          ## 安装

          ```bash
          npm install test-cloud-testez@${{ steps.get_version.outputs.VERSION }}
          ```

          ## 文档

          请查看 [README.md](https://github.com/white-dragon-core/test-cloud-testez#readme) 了解详细使用说明。
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to npm
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        if [ -z "$NODE_AUTH_TOKEN" ]; then
          echo "⚠️ Skipping npm publish - NPM_TOKEN not configured in repository secrets"
          echo "ℹ️ To enable npm publishing, add NPM_TOKEN secret"
          exit 0
        fi
        npm publish
